In [ ]:
import numpy as np
#attributes of numpy
arr=np.array(([1,2,3,4,5],[2,6,7,8,9]))
print(arr)
print(arr.ndim) #number of dimensions
print(arr.shape) #shape of the array
print(arr.dtype) #size of the array


[[1 2 3 4 5]
 [2 6 7 8 9]]
2
(2, 5)


In [6]:
arr=np.array(([1,2,3,4,5],[2,6,7,8,"ABC"]))
print(arr)
print(np.arange(3))
print(np.arange(3,10))
print(np.random.rand(3,5))
print(np.random.randint(1,100,10)) #start, stop, size

[['1' '2' '3' '4' '5']
 ['2' '6' '7' '8' 'ABC']]
[0 1 2]
[3 4 5 6 7 8 9]
[[0.62690807 0.13869631 0.59761924 0.36094995 0.85084927]
 [0.59158917 0.02665762 0.71911921 0.21885861 0.57898989]
 [0.96052012 0.26811985 0.2558269  0.88333911 0.37272947]]
[55 51 94 50 34 34 24 38 42 93]


In [7]:
import numpy as np

ans = np.random.randint(1, 101)  # Random number between 1 and 100

while True:
    a = int(input("Guess the number: "))

    if a == ans:
        print("Correct! You guessed the number.")
        break

    b = ans - a

    if b > 0:
        print("Too small!")
    else:
        print("Too big!")

Too big!
Too big!
Too big!
Too big!
Too small!
Too small!
Too small!
Too small!
Correct! You guessed the number.


In [9]:
#zeros
print(np.zeros((3,4), dtype=int)) #3 rows and 4 columns

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [11]:
#ones
print(np.ones((3,4), dtype=int)) #3 rows and 4 columns

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
arr=np.random.randint(1,100,10) #start, stop, size
print(arr)
print(arr.shape)
print(arr.reshape(2,5)) #reshape the array to 2 rows and 5 columns

[57 59 74  8 12 61 83 99 66 70]
(10,)
[[57 59 74  8 12]
 [61 83 99 66 70]]


In [13]:
#max min argmax argmin
print(arr)
print("Max:", arr.max())
print("Min:", arr.min())
print("Index of Max:", arr.argmax())
print("Index of Min:", arr.argmin())    

[57 59 74  8 12 61 83 99 66 70]
Max: 99
Min: 8
Index of Max: 7
Index of Min: 3


In [15]:
#mean median std
print("Mean:", arr.mean())
print("Median:", np.median(arr))
print("Standard Deviation:", arr.std())

Mean: 58.9
Median: 63.5
Standard Deviation: 27.18253115513712


In [19]:
print(np.arange(1, 10, 2) )#start, stop, step

[1 3 5 7 9]


In [20]:
arr=arr.reshape(2,5)
print(arr)


[[57 59 74  8 12]
 [61 83 99 66 70]]


In [22]:
print(arr.flatten())
print(arr.ravel())

[57 59 74  8 12 61 83 99 66 70]
[57 59 74  8 12 61 83 99 66 70]
